name: Moo3DCarousel
author: Patouche
current: 1.0
category: Effects
tags: [scroll,images,carousel]
docs: http://www.farkess.com/~patouche/tuto-mootools/carrousel-3d/doc.html
demo: http://www.farkess.com/~patouche/tuto-mootools/carrousel-3d/